name: Deploy

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v3'

    - uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - id: 'deploy'
      name: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v0'
      with:
        working_directory: 'server/'
        deliverables: 'app.yaml'
        project_id: '${{ secrets.GCP_PROJECT }}'

    - name: 'show output'
      run: 'echo ${{ steps.deploy.outputs.url }}'
